CXX      = g++
CXXFLAGS = -Wall -Wextra -std=c++17 -O2
TARGET   = wordsrch
TESTS    = wordsrch_tests

# Everything except main(). Both the program and the test harness link these.
LIB_SRCS = puzzle.cpp wordlist.cpp String.cpp Exception.cpp attempt.cpp rndm.cpp
SRCS     = wordsrch.cpp $(LIB_SRCS)
TEST_SRCS = tests.cpp $(LIB_SRCS)

OBJS      = $(SRCS:.cpp=.o)
TEST_OBJS = $(TEST_SRCS:.cpp=.o)

# Header dependencies are generated by the compiler (-MMD -MP) instead of being
# listed by hand. A hand-written list silently goes stale: miss one #include and
# make stops rebuilding a file that needed rebuilding.
DEPS = $(OBJS:.o=.d) $(TEST_OBJS:.o=.d)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

$(TESTS): $(TEST_OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -MMD -MP -c -o $@ $<

# Run the unit tests, then drive the real binary against the sample word lists.
# The fixture script covers the input validation, which lives behind main() and
# so is out of reach of the unit tests.
test: $(TESTS) $(TARGET)
	./$(TESTS)
	@echo
	@sh fixtures_test.sh

# Unoptimised build with debug symbols.
debug: CXXFLAGS = -Wall -Wextra -std=c++17 -O0 -g
debug: clean $(TARGET)

# Address and undefined-behaviour sanitizers. This configuration is what
# catches uninitialised reads, buffer overruns and leaks; -Wall alone does not.
asan: CXXFLAGS = -Wall -Wextra -std=c++17 -O1 -g -fsanitize=address,undefined \
                 -fno-omit-frame-pointer
asan: clean $(TESTS)
	./$(TESTS)

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(OBJS) $(TEST_OBJS) $(DEPS) $(TARGET) $(TESTS)

-include $(DEPS)

.PHONY: all clean run test debug asan
